ALTER TABLE IF EXISTS "contact"
ADD COLUMN IF NOT EXISTS "confess_target" INTEGER CONSTRAINT "contact_confess_group_fk" REFERENCES "group" (id) ON DELETE
SET NULL ON UPDATE CASCADE;
ALTER TABLE IF EXISTS "group"
ADD COLUMN IF NOT EXISTS "is_announcement" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS "group_settings"
ADD COLUMN IF NOT EXISTS "is_confess_allowed" BOOLEAN NOT NULL DEFAULT FALSE;